// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.CarServer.ChargeSchedule', null, global);
goog.exportSymbol('proto.CarServer.Invalid', null, global);
goog.exportSymbol('proto.CarServer.LatLong', null, global);
goog.exportSymbol('proto.CarServer.OffPeakChargingTimes', null, global);
goog.exportSymbol('proto.CarServer.OffPeakChargingTimes.TimesCase', null, global);
goog.exportSymbol('proto.CarServer.PreconditionSchedule', null, global);
goog.exportSymbol('proto.CarServer.PreconditioningTimes', null, global);
goog.exportSymbol('proto.CarServer.PreconditioningTimes.TimesCase', null, global);
goog.exportSymbol('proto.CarServer.Void', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.Void = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.Void, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.Void.displayName = 'proto.CarServer.Void';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.LatLong = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.LatLong, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.LatLong.displayName = 'proto.CarServer.LatLong';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.PreconditioningTimes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.CarServer.PreconditioningTimes.oneofGroups_);
};
goog.inherits(proto.CarServer.PreconditioningTimes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.PreconditioningTimes.displayName = 'proto.CarServer.PreconditioningTimes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.OffPeakChargingTimes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.CarServer.OffPeakChargingTimes.oneofGroups_);
};
goog.inherits(proto.CarServer.OffPeakChargingTimes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.OffPeakChargingTimes.displayName = 'proto.CarServer.OffPeakChargingTimes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.ChargeSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.ChargeSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.ChargeSchedule.displayName = 'proto.CarServer.ChargeSchedule';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.PreconditionSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.PreconditionSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.PreconditionSchedule.displayName = 'proto.CarServer.PreconditionSchedule';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.Void.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.Void.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.Void} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.Void.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.Void}
 */
proto.CarServer.Void.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.Void;
  return proto.CarServer.Void.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.Void} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.Void}
 */
proto.CarServer.Void.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.Void.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.Void.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.Void} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.Void.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.LatLong.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.LatLong.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.LatLong} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.LatLong.toObject = function(includeInstance, msg) {
  var f, obj = {
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.LatLong}
 */
proto.CarServer.LatLong.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.LatLong;
  return proto.CarServer.LatLong.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.LatLong} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.LatLong}
 */
proto.CarServer.LatLong.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLatitude(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLongitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.LatLong.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.LatLong.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.LatLong} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.LatLong.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional float latitude = 1;
 * @return {number}
 */
proto.CarServer.LatLong.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.LatLong} returns this
 */
proto.CarServer.LatLong.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float longitude = 2;
 * @return {number}
 */
proto.CarServer.LatLong.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.LatLong} returns this
 */
proto.CarServer.LatLong.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.CarServer.PreconditioningTimes.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.CarServer.PreconditioningTimes.TimesCase = {
  TIMES_NOT_SET: 0,
  ALL_WEEK: 1,
  WEEKDAYS: 2
};

/**
 * @return {proto.CarServer.PreconditioningTimes.TimesCase}
 */
proto.CarServer.PreconditioningTimes.prototype.getTimesCase = function() {
  return /** @type {proto.CarServer.PreconditioningTimes.TimesCase} */(jspb.Message.computeOneofCase(this, proto.CarServer.PreconditioningTimes.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.PreconditioningTimes.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.PreconditioningTimes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.PreconditioningTimes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.PreconditioningTimes.toObject = function(includeInstance, msg) {
  var f, obj = {
    allWeek: (f = msg.getAllWeek()) && proto.CarServer.Void.toObject(includeInstance, f),
    weekdays: (f = msg.getWeekdays()) && proto.CarServer.Void.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.PreconditioningTimes}
 */
proto.CarServer.PreconditioningTimes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.PreconditioningTimes;
  return proto.CarServer.PreconditioningTimes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.PreconditioningTimes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.PreconditioningTimes}
 */
proto.CarServer.PreconditioningTimes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.CarServer.Void;
      reader.readMessage(value,proto.CarServer.Void.deserializeBinaryFromReader);
      msg.setAllWeek(value);
      break;
    case 2:
      var value = new proto.CarServer.Void;
      reader.readMessage(value,proto.CarServer.Void.deserializeBinaryFromReader);
      msg.setWeekdays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.PreconditioningTimes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.PreconditioningTimes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.PreconditioningTimes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.PreconditioningTimes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllWeek();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.CarServer.Void.serializeBinaryToWriter
    );
  }
  f = message.getWeekdays();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.CarServer.Void.serializeBinaryToWriter
    );
  }
};


/**
 * optional Void all_week = 1;
 * @return {?proto.CarServer.Void}
 */
proto.CarServer.PreconditioningTimes.prototype.getAllWeek = function() {
  return /** @type{?proto.CarServer.Void} */ (
    jspb.Message.getWrapperField(this, proto.CarServer.Void, 1));
};


/**
 * @param {?proto.CarServer.Void|undefined} value
 * @return {!proto.CarServer.PreconditioningTimes} returns this
*/
proto.CarServer.PreconditioningTimes.prototype.setAllWeek = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.CarServer.PreconditioningTimes.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CarServer.PreconditioningTimes} returns this
 */
proto.CarServer.PreconditioningTimes.prototype.clearAllWeek = function() {
  return this.setAllWeek(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CarServer.PreconditioningTimes.prototype.hasAllWeek = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Void weekdays = 2;
 * @return {?proto.CarServer.Void}
 */
proto.CarServer.PreconditioningTimes.prototype.getWeekdays = function() {
  return /** @type{?proto.CarServer.Void} */ (
    jspb.Message.getWrapperField(this, proto.CarServer.Void, 2));
};


/**
 * @param {?proto.CarServer.Void|undefined} value
 * @return {!proto.CarServer.PreconditioningTimes} returns this
*/
proto.CarServer.PreconditioningTimes.prototype.setWeekdays = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.CarServer.PreconditioningTimes.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CarServer.PreconditioningTimes} returns this
 */
proto.CarServer.PreconditioningTimes.prototype.clearWeekdays = function() {
  return this.setWeekdays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CarServer.PreconditioningTimes.prototype.hasWeekdays = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.CarServer.OffPeakChargingTimes.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.CarServer.OffPeakChargingTimes.TimesCase = {
  TIMES_NOT_SET: 0,
  ALL_WEEK: 1,
  WEEKDAYS: 2
};

/**
 * @return {proto.CarServer.OffPeakChargingTimes.TimesCase}
 */
proto.CarServer.OffPeakChargingTimes.prototype.getTimesCase = function() {
  return /** @type {proto.CarServer.OffPeakChargingTimes.TimesCase} */(jspb.Message.computeOneofCase(this, proto.CarServer.OffPeakChargingTimes.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.OffPeakChargingTimes.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.OffPeakChargingTimes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.OffPeakChargingTimes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.OffPeakChargingTimes.toObject = function(includeInstance, msg) {
  var f, obj = {
    allWeek: (f = msg.getAllWeek()) && proto.CarServer.Void.toObject(includeInstance, f),
    weekdays: (f = msg.getWeekdays()) && proto.CarServer.Void.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.OffPeakChargingTimes}
 */
proto.CarServer.OffPeakChargingTimes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.OffPeakChargingTimes;
  return proto.CarServer.OffPeakChargingTimes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.OffPeakChargingTimes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.OffPeakChargingTimes}
 */
proto.CarServer.OffPeakChargingTimes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.CarServer.Void;
      reader.readMessage(value,proto.CarServer.Void.deserializeBinaryFromReader);
      msg.setAllWeek(value);
      break;
    case 2:
      var value = new proto.CarServer.Void;
      reader.readMessage(value,proto.CarServer.Void.deserializeBinaryFromReader);
      msg.setWeekdays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.OffPeakChargingTimes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.OffPeakChargingTimes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.OffPeakChargingTimes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.OffPeakChargingTimes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllWeek();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.CarServer.Void.serializeBinaryToWriter
    );
  }
  f = message.getWeekdays();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.CarServer.Void.serializeBinaryToWriter
    );
  }
};


/**
 * optional Void all_week = 1;
 * @return {?proto.CarServer.Void}
 */
proto.CarServer.OffPeakChargingTimes.prototype.getAllWeek = function() {
  return /** @type{?proto.CarServer.Void} */ (
    jspb.Message.getWrapperField(this, proto.CarServer.Void, 1));
};


/**
 * @param {?proto.CarServer.Void|undefined} value
 * @return {!proto.CarServer.OffPeakChargingTimes} returns this
*/
proto.CarServer.OffPeakChargingTimes.prototype.setAllWeek = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.CarServer.OffPeakChargingTimes.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CarServer.OffPeakChargingTimes} returns this
 */
proto.CarServer.OffPeakChargingTimes.prototype.clearAllWeek = function() {
  return this.setAllWeek(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CarServer.OffPeakChargingTimes.prototype.hasAllWeek = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Void weekdays = 2;
 * @return {?proto.CarServer.Void}
 */
proto.CarServer.OffPeakChargingTimes.prototype.getWeekdays = function() {
  return /** @type{?proto.CarServer.Void} */ (
    jspb.Message.getWrapperField(this, proto.CarServer.Void, 2));
};


/**
 * @param {?proto.CarServer.Void|undefined} value
 * @return {!proto.CarServer.OffPeakChargingTimes} returns this
*/
proto.CarServer.OffPeakChargingTimes.prototype.setWeekdays = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.CarServer.OffPeakChargingTimes.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CarServer.OffPeakChargingTimes} returns this
 */
proto.CarServer.OffPeakChargingTimes.prototype.clearWeekdays = function() {
  return this.setWeekdays(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CarServer.OffPeakChargingTimes.prototype.hasWeekdays = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.ChargeSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.ChargeSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.ChargeSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.ChargeSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    daysOfWeek: jspb.Message.getFieldWithDefault(msg, 3, 0),
    startEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    startTime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    endEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    endTime: jspb.Message.getFieldWithDefault(msg, 7, 0),
    oneTime: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.ChargeSchedule}
 */
proto.CarServer.ChargeSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.ChargeSchedule;
  return proto.CarServer.ChargeSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.ChargeSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.ChargeSchedule}
 */
proto.CarServer.ChargeSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaysOfWeek(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStartEnabled(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStartTime(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEndEnabled(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEndTime(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOneTime(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLatitude(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLongitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.ChargeSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.ChargeSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.ChargeSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.ChargeSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDaysOfWeek();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getStartEnabled();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getStartTime();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getEndEnabled();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getEndTime();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getOneTime();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeFloat(
      11,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.CarServer.ChargeSchedule.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 days_of_week = 3;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getDaysOfWeek = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setDaysOfWeek = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool start_enabled = 4;
 * @return {boolean}
 */
proto.CarServer.ChargeSchedule.prototype.getStartEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setStartEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int32 start_time = 5;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getStartTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setStartTime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool end_enabled = 6;
 * @return {boolean}
 */
proto.CarServer.ChargeSchedule.prototype.getEndEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setEndEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional int32 end_time = 7;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getEndTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setEndTime = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional bool one_time = 8;
 * @return {boolean}
 */
proto.CarServer.ChargeSchedule.prototype.getOneTime = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setOneTime = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool enabled = 9;
 * @return {boolean}
 */
proto.CarServer.ChargeSchedule.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional float latitude = 10;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional float longitude = 11;
 * @return {number}
 */
proto.CarServer.ChargeSchedule.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.ChargeSchedule} returns this
 */
proto.CarServer.ChargeSchedule.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.PreconditionSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.PreconditionSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.PreconditionSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.PreconditionSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    daysOfWeek: jspb.Message.getFieldWithDefault(msg, 3, 0),
    preconditionTime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    oneTime: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.PreconditionSchedule}
 */
proto.CarServer.PreconditionSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.PreconditionSchedule;
  return proto.CarServer.PreconditionSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.PreconditionSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.PreconditionSchedule}
 */
proto.CarServer.PreconditionSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDaysOfWeek(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreconditionTime(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOneTime(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLatitude(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLongitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.PreconditionSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.PreconditionSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.PreconditionSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.PreconditionSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDaysOfWeek();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getPreconditionTime();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getOneTime();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.CarServer.PreconditionSchedule.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.CarServer.PreconditionSchedule.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 days_of_week = 3;
 * @return {number}
 */
proto.CarServer.PreconditionSchedule.prototype.getDaysOfWeek = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setDaysOfWeek = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 precondition_time = 4;
 * @return {number}
 */
proto.CarServer.PreconditionSchedule.prototype.getPreconditionTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setPreconditionTime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bool one_time = 5;
 * @return {boolean}
 */
proto.CarServer.PreconditionSchedule.prototype.getOneTime = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setOneTime = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool enabled = 6;
 * @return {boolean}
 */
proto.CarServer.PreconditionSchedule.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional float latitude = 7;
 * @return {number}
 */
proto.CarServer.PreconditionSchedule.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float longitude = 8;
 * @return {number}
 */
proto.CarServer.PreconditionSchedule.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CarServer.PreconditionSchedule} returns this
 */
proto.CarServer.PreconditionSchedule.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * @enum {number}
 */
proto.CarServer.Invalid = {
  INVALID: 0
};

goog.object.extend(exports, proto.CarServer);
