// source: vehicle.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.CarServer.ClimateState', null, global);
goog.exportSymbol('proto.CarServer.ClimateState.CopActivationTemp', null, global);
goog.exportSymbol('proto.CarServer.VehicleState', null, global);
goog.exportSymbol('proto.CarServer.VehicleState.GuestMode', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.VehicleState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.VehicleState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.VehicleState.displayName = 'proto.CarServer.VehicleState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.VehicleState.GuestMode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.VehicleState.GuestMode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.VehicleState.GuestMode.displayName = 'proto.CarServer.VehicleState.GuestMode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CarServer.ClimateState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CarServer.ClimateState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CarServer.ClimateState.displayName = 'proto.CarServer.ClimateState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.VehicleState.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.VehicleState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.VehicleState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.VehicleState.toObject = function(includeInstance, msg) {
  var f, obj = {
    guestmode: (f = msg.getGuestmode()) && proto.CarServer.VehicleState.GuestMode.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.VehicleState}
 */
proto.CarServer.VehicleState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.VehicleState;
  return proto.CarServer.VehicleState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.VehicleState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.VehicleState}
 */
proto.CarServer.VehicleState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 74:
      var value = new proto.CarServer.VehicleState.GuestMode;
      reader.readMessage(value,proto.CarServer.VehicleState.GuestMode.deserializeBinaryFromReader);
      msg.setGuestmode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.VehicleState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.VehicleState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.VehicleState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.VehicleState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGuestmode();
  if (f != null) {
    writer.writeMessage(
      74,
      f,
      proto.CarServer.VehicleState.GuestMode.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.VehicleState.GuestMode.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.VehicleState.GuestMode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.VehicleState.GuestMode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.VehicleState.GuestMode.toObject = function(includeInstance, msg) {
  var f, obj = {
    guestmodeactive: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.VehicleState.GuestMode}
 */
proto.CarServer.VehicleState.GuestMode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.VehicleState.GuestMode;
  return proto.CarServer.VehicleState.GuestMode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.VehicleState.GuestMode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.VehicleState.GuestMode}
 */
proto.CarServer.VehicleState.GuestMode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGuestmodeactive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.VehicleState.GuestMode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.VehicleState.GuestMode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.VehicleState.GuestMode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.VehicleState.GuestMode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGuestmodeactive();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool GuestModeActive = 1;
 * @return {boolean}
 */
proto.CarServer.VehicleState.GuestMode.prototype.getGuestmodeactive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CarServer.VehicleState.GuestMode} returns this
 */
proto.CarServer.VehicleState.GuestMode.prototype.setGuestmodeactive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional GuestMode guestMode = 74;
 * @return {?proto.CarServer.VehicleState.GuestMode}
 */
proto.CarServer.VehicleState.prototype.getGuestmode = function() {
  return /** @type{?proto.CarServer.VehicleState.GuestMode} */ (
    jspb.Message.getWrapperField(this, proto.CarServer.VehicleState.GuestMode, 74));
};


/**
 * @param {?proto.CarServer.VehicleState.GuestMode|undefined} value
 * @return {!proto.CarServer.VehicleState} returns this
*/
proto.CarServer.VehicleState.prototype.setGuestmode = function(value) {
  return jspb.Message.setWrapperField(this, 74, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CarServer.VehicleState} returns this
 */
proto.CarServer.VehicleState.prototype.clearGuestmode = function() {
  return this.setGuestmode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CarServer.VehicleState.prototype.hasGuestmode = function() {
  return jspb.Message.getField(this, 74) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CarServer.ClimateState.prototype.toObject = function(opt_includeInstance) {
  return proto.CarServer.ClimateState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CarServer.ClimateState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.ClimateState.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CarServer.ClimateState}
 */
proto.CarServer.ClimateState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CarServer.ClimateState;
  return proto.CarServer.ClimateState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CarServer.ClimateState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CarServer.ClimateState}
 */
proto.CarServer.ClimateState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CarServer.ClimateState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CarServer.ClimateState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CarServer.ClimateState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CarServer.ClimateState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.CarServer.ClimateState.CopActivationTemp = {
  COPACTIVATIONTEMPUNSPECIFIED: 0,
  COPACTIVATIONTEMPLOW: 1,
  COPACTIVATIONTEMPMEDIUM: 2,
  COPACTIVATIONTEMPHIGH: 3
};

goog.object.extend(exports, proto.CarServer);
